Building WebKit also requires flex
On some (minimal) Linux installations, flex is not present, and WebKit
requires it to build, or will display the following build output:

building WebKit
/home/vagrant/isis
ERROR: flex missing but required to build WebKit.
Failed to make WebKit
Failed to build: WebKit